-- Script para crear la tabla y poblarla con palabras (español, árabe)
DROP TABLE IF EXISTS diccionario;
CREATE TABLE diccionario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    es TEXT NOT NULL,
    ar TEXT NOT NULL
);

INSERT INTO diccionario (es, ar) VALUES
('mesa','طاولة'),
('silla','كرسي'),
('ventana','نافذة'),
('puerta','باب'),
('pared','جدار'),
('techo','سقف'),
('suelo','أرضية'),
('coche','سيارة'),
('camión','شاحنة'),
('bicicleta','دراجة'),
('moto','دراجة نارية'),
('avión','طائرة'),
('tren','قطار'),
('barco','سفينة'),
('autobús','حافلة'),
('calle','شارع'),
('carretera','طريق'),
('puente','جسر'),
('semáforo','إشارة مرور'),
('parada','محطة'),
('metro','مترو'),
('billete','تذكرة'),
('maleta','حقيبة سفر'),
('pasaporte','جواز سفر'),
('hotel','فندق'),
('restaurante','مطعم'),
('cafetería','مقهى'),
('supermercado','سوبر ماركت'),
('mercado','سوق'),
('farmacia','صيدلية'),
('hospital','مستشفى'),
('clínica','عيادة'),
('escuela','مدرسة'),
('colegio','كلية'),
('universidad','جامعة'),
('biblioteca','مكتبة'),
('libro','كتاب'),
('cuaderno','دفتر'),
('lápiz','قلم رصاص'),
('bolígrafo','قلم'),
('papel','ورق'),
('borrador','ممحاة'),
('regla','مسطرة'),
('mochila','حقيبة ظهر'),
('ordenador','كمبيوتر'),
('móvil','هاتف محمول'),
('radio','راديو'),
('televisión','تلفاز'),
('internet','إنترنت'),
('correo','بريد'),
('mensaje','رسالة'),
('foto','صورة'),
('vídeo','فيديو'),
('aplicación','تطبيق'),
('programa','برنامج'),
('usuario','مستخدم'),
('contraseña','كلمة مرور'),
('cuenta','حساب'),
('archivo','ملف'),
('carpeta','مجلد'),
('ratón','فأرة'),
('teclado','لوحة مفاتيح'),
('pantalla','شاشة'),
('cargador','شاحن'),
('batería','بطارية'),
('cable','كابل'),
('botón','زر'),
('sofá','أريكة'),
('cama','سرير'),
('almohada','وسادة'),
('manta','بطانية'),
('sábana','ملاءة'),
('colchón','مرتبة'),
('armario','خزانة'),
('cajón','درج'),
('estante','رف'),
('lámpara','مصباح'),
('luz','ضوء'),
('sombra','ظل'),
('espejo','مرآة'),
('reloj','ساعة'),
('cuadro','لوحة'),
('persiana','ستارة'),
('balcón','شرفة'),
('terraza','شرفة'),
('jardín','حديقة'),
('planta','نبتة'),
('flor','زهرة'),
('árbol','شجرة'),
('césped','عشب'),
('fruta','فاكهة'),
('verdura','خضار'),
('pan','خبز'),
('leche','حليب'),
('queso','جبن'),
('huevo','بيضة'),
('carne','لحم'),
('pollo','دجاج'),
('pescado','سمك'),
('arroz','أرز'),
('pasta','معكرونة'),
('sal','ملح'),
('azúcar','سكر'),
('aceite','زيت'),
('mantequilla','زبدة'),
('café','قهوة'),
('zumo','عصير'),
('agua','ماء'),
('cerveza','بيرة'),
('vino','نبيذ'),
('manzana','تفاحة'),
('naranja','برتقالة'),
('plátano','موز'),
('limón','ليمون'),
('uva','عنب'),
('pera','كمثرى'),
('melón','بطيخ'),
('sandía','بطيخ أحمر'),
('piña','أناناس'),
('fresa','فراولة'),
('cereza','كرز'),
('melocotón','خوخ'),
('albaricoque','مشمش'),
('ciruela','برقوق'),
('higo','تين'),
('kiwi','كيوي'),
('aguacate','أفوكادو'),
('zanahoria','جزر'),
('patata','بطاطس'),
('cebolla','بصل'),
('tomate','طماطم'),
('lechuga','خس'),
('pepino','خيار'),
('calabacín','كوسة'),
('berenjena','باذنجان'),
('pimiento','فلفل'),
('espinaca','سبانخ'),
('brócoli','بروكلي'),
('col','كرنب'),
('apio','كرفس'),
('ajo','ثوم'),
('maíz','ذرة'),
('seta','فطر'),
('champiñón','فطر'),
('judía','فاصوليا'),
('guisante','بازلاء'),
('lenteja','عدس'),
('garbanzos','حمص'),
('habas','فول'),
('soja','صويا'),
('almendra','لوز'),
('nuez','جوز'),
('cacahuete','فول سوداني'),
('avellana','بندق'),
('castaña','كستناء'),
('pistacho','فستق'),
('anacardo','كاجو'),
('semilla','بذرة'),
('cereal','حبوب'),
('trigo','قمح'),
('arroz','أرز'),
('avena','شوفان'),
('maíz','ذرة'),
('centeno','جاودار'),
('cebada','شعير'),
('pan','خبز'),
('pastel','كعكة'),
('galleta','بسكويت'),
('chocolate','شوكولاتة'),
('caramelo','كراميل'),
('helado','آيس كريم'),
('azúcar','سكر'),
('sal','ملح'),
('pimienta','فلفل'),
('vinagre','خل'),
('mostaza','خردل'),
('mayonesa','مايونيز'),
('ketchup','كاتشب'),
('salsa','صلصة'),
('sopa','حساء'),
('ensalada','سلطة'),
('pizza','بيتزا'),
('hamburguesa','برجر'),
('bocadillo','شطيرة'),
('sándwich','ساندويتش'),
('patatas fritas','بطاطس مقلية'),
('omelette','عجة'),
('paella','باييا'),
('tortilla','تورتيلا'),
('marisco','مأكولات بحرية'),
('langosta','جراد البحر'),
('cangrejo','سلطعون'),
('camarón','جمبري'),
('mejillón','بلح البحر'),
('almeja','محار'),
('ostra','محار'),
('calamar','حبار'),
('pulpo','أخطبوط'),
('atún','تونة'),
('sardina','سردين'),
('bacalao','سمك القد'),
('merluza','ميرلو'),
('salmonete','سمك السلمون'),
('trucha','سلمون مرقط'),
('caracol','حلزون'),
('conejo','أرنب'),
('cordero','خروف'),
('ternera','عجل'),
('cerdo','خنزير'),
('vaca','بقرة'),
('pavo','ديك رومي'),
('pato','بطة'),
('oca','إوزة'),
('caballo','حصان'),
('burro','حمار'),
('mula','بغل'),
('oveja','خروف'),
('cabra','ماعز'),
('buey','ثور'),
('ratón','فأر'),
('rata','جرذ'),
('zorro','ثعلب'),
('lobo','ذئب'),
('oso','دب'),
('ciervo','غزال'),
('jabalí','خنزير بري'),
('jirafa','زرافة'),
('cebra','حمار وحشي'),
('león','أسد'),
('tigre','نمر'),
('leopardo','فهد'),
('pantera','نمر أسود'),
('mono','قرد'),
('chimpancé','شمبانزي'),
('gorila','غوريلا'),
('orangután','إنسان الغاب'),
('murciélago','خفاش'),
('elefante','فيل'),
('rinoceronte','وحيد القرن'),
('hipopótamo','فرس النهر');
